# 基礎鏡像，適配 Java 21
FROM openjdk:21-jdk-slim

# 設定容器中的工作目錄
WORKDIR /app

# 將 JAR 檔案複製到容器中
COPY target/docker-0.0.1-SNAPSHOT.jar app.jar

# 暴露 Spring Boot 預設的運行端口
EXPOSE 8080

# 啟動應用
ENTRYPOINT ["java", "-jar", "app.jar"]